min_value: 1046.0
max_value: 2065.0
joint_state_topic: /left/gripper/dynamixel_motor/joint_states
command_topic: /left/gripper/dynamixel_motor/command
enable_torque_service: /left/gripper/dynamixel_motor/set_torque
